require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CursodisciplinaprofessorsController do

  # This should return the minimal set of attributes required to create a valid
  # Cursodisciplinaprofessor. As you add validations to Cursodisciplinaprofessor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CursodisciplinaprofessorsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cursodisciplinaprofessors as @cursodisciplinaprofessors" do
      cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cursodisciplinaprofessors).should eq([cursodisciplinaprofessor])
    end
  end

  describe "GET show" do
    it "assigns the requested cursodisciplinaprofessor as @cursodisciplinaprofessor" do
      cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
      get :show, {:id => cursodisciplinaprofessor.to_param}, valid_session
      assigns(:cursodisciplinaprofessor).should eq(cursodisciplinaprofessor)
    end
  end

  describe "GET new" do
    it "assigns a new cursodisciplinaprofessor as @cursodisciplinaprofessor" do
      get :new, {}, valid_session
      assigns(:cursodisciplinaprofessor).should be_a_new(Cursodisciplinaprofessor)
    end
  end

  describe "GET edit" do
    it "assigns the requested cursodisciplinaprofessor as @cursodisciplinaprofessor" do
      cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
      get :edit, {:id => cursodisciplinaprofessor.to_param}, valid_session
      assigns(:cursodisciplinaprofessor).should eq(cursodisciplinaprofessor)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cursodisciplinaprofessor" do
        expect {
          post :create, {:cursodisciplinaprofessor => valid_attributes}, valid_session
        }.to change(Cursodisciplinaprofessor, :count).by(1)
      end

      it "assigns a newly created cursodisciplinaprofessor as @cursodisciplinaprofessor" do
        post :create, {:cursodisciplinaprofessor => valid_attributes}, valid_session
        assigns(:cursodisciplinaprofessor).should be_a(Cursodisciplinaprofessor)
        assigns(:cursodisciplinaprofessor).should be_persisted
      end

      it "redirects to the created cursodisciplinaprofessor" do
        post :create, {:cursodisciplinaprofessor => valid_attributes}, valid_session
        response.should redirect_to(Cursodisciplinaprofessor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cursodisciplinaprofessor as @cursodisciplinaprofessor" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessor.any_instance.stub(:save).and_return(false)
        post :create, {:cursodisciplinaprofessor => {}}, valid_session
        assigns(:cursodisciplinaprofessor).should be_a_new(Cursodisciplinaprofessor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessor.any_instance.stub(:save).and_return(false)
        post :create, {:cursodisciplinaprofessor => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cursodisciplinaprofessor" do
        cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
        # Assuming there are no other cursodisciplinaprofessors in the database, this
        # specifies that the Cursodisciplinaprofessor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cursodisciplinaprofessor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cursodisciplinaprofessor.to_param, :cursodisciplinaprofessor => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cursodisciplinaprofessor as @cursodisciplinaprofessor" do
        cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
        put :update, {:id => cursodisciplinaprofessor.to_param, :cursodisciplinaprofessor => valid_attributes}, valid_session
        assigns(:cursodisciplinaprofessor).should eq(cursodisciplinaprofessor)
      end

      it "redirects to the cursodisciplinaprofessor" do
        cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
        put :update, {:id => cursodisciplinaprofessor.to_param, :cursodisciplinaprofessor => valid_attributes}, valid_session
        response.should redirect_to(cursodisciplinaprofessor)
      end
    end

    describe "with invalid params" do
      it "assigns the cursodisciplinaprofessor as @cursodisciplinaprofessor" do
        cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessor.any_instance.stub(:save).and_return(false)
        put :update, {:id => cursodisciplinaprofessor.to_param, :cursodisciplinaprofessor => {}}, valid_session
        assigns(:cursodisciplinaprofessor).should eq(cursodisciplinaprofessor)
      end

      it "re-renders the 'edit' template" do
        cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessor.any_instance.stub(:save).and_return(false)
        put :update, {:id => cursodisciplinaprofessor.to_param, :cursodisciplinaprofessor => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cursodisciplinaprofessor" do
      cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
      expect {
        delete :destroy, {:id => cursodisciplinaprofessor.to_param}, valid_session
      }.to change(Cursodisciplinaprofessor, :count).by(-1)
    end

    it "redirects to the cursodisciplinaprofessors list" do
      cursodisciplinaprofessor = Cursodisciplinaprofessor.create! valid_attributes
      delete :destroy, {:id => cursodisciplinaprofessor.to_param}, valid_session
      response.should redirect_to(cursodisciplinaprofessors_url)
    end
  end

end
