require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CursodisciplinaprofessoranoletivosController do

  # This should return the minimal set of attributes required to create a valid
  # Cursodisciplinaprofessoranoletivo. As you add validations to Cursodisciplinaprofessoranoletivo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CursodisciplinaprofessoranoletivosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cursodisciplinaprofessoranoletivos as @cursodisciplinaprofessoranoletivos" do
      cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cursodisciplinaprofessoranoletivos).should eq([cursodisciplinaprofessoranoletivo])
    end
  end

  describe "GET show" do
    it "assigns the requested cursodisciplinaprofessoranoletivo as @cursodisciplinaprofessoranoletivo" do
      cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
      get :show, {:id => cursodisciplinaprofessoranoletivo.to_param}, valid_session
      assigns(:cursodisciplinaprofessoranoletivo).should eq(cursodisciplinaprofessoranoletivo)
    end
  end

  describe "GET new" do
    it "assigns a new cursodisciplinaprofessoranoletivo as @cursodisciplinaprofessoranoletivo" do
      get :new, {}, valid_session
      assigns(:cursodisciplinaprofessoranoletivo).should be_a_new(Cursodisciplinaprofessoranoletivo)
    end
  end

  describe "GET edit" do
    it "assigns the requested cursodisciplinaprofessoranoletivo as @cursodisciplinaprofessoranoletivo" do
      cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
      get :edit, {:id => cursodisciplinaprofessoranoletivo.to_param}, valid_session
      assigns(:cursodisciplinaprofessoranoletivo).should eq(cursodisciplinaprofessoranoletivo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cursodisciplinaprofessoranoletivo" do
        expect {
          post :create, {:cursodisciplinaprofessoranoletivo => valid_attributes}, valid_session
        }.to change(Cursodisciplinaprofessoranoletivo, :count).by(1)
      end

      it "assigns a newly created cursodisciplinaprofessoranoletivo as @cursodisciplinaprofessoranoletivo" do
        post :create, {:cursodisciplinaprofessoranoletivo => valid_attributes}, valid_session
        assigns(:cursodisciplinaprofessoranoletivo).should be_a(Cursodisciplinaprofessoranoletivo)
        assigns(:cursodisciplinaprofessoranoletivo).should be_persisted
      end

      it "redirects to the created cursodisciplinaprofessoranoletivo" do
        post :create, {:cursodisciplinaprofessoranoletivo => valid_attributes}, valid_session
        response.should redirect_to(Cursodisciplinaprofessoranoletivo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cursodisciplinaprofessoranoletivo as @cursodisciplinaprofessoranoletivo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessoranoletivo.any_instance.stub(:save).and_return(false)
        post :create, {:cursodisciplinaprofessoranoletivo => {}}, valid_session
        assigns(:cursodisciplinaprofessoranoletivo).should be_a_new(Cursodisciplinaprofessoranoletivo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessoranoletivo.any_instance.stub(:save).and_return(false)
        post :create, {:cursodisciplinaprofessoranoletivo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cursodisciplinaprofessoranoletivo" do
        cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
        # Assuming there are no other cursodisciplinaprofessoranoletivos in the database, this
        # specifies that the Cursodisciplinaprofessoranoletivo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cursodisciplinaprofessoranoletivo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cursodisciplinaprofessoranoletivo.to_param, :cursodisciplinaprofessoranoletivo => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cursodisciplinaprofessoranoletivo as @cursodisciplinaprofessoranoletivo" do
        cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
        put :update, {:id => cursodisciplinaprofessoranoletivo.to_param, :cursodisciplinaprofessoranoletivo => valid_attributes}, valid_session
        assigns(:cursodisciplinaprofessoranoletivo).should eq(cursodisciplinaprofessoranoletivo)
      end

      it "redirects to the cursodisciplinaprofessoranoletivo" do
        cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
        put :update, {:id => cursodisciplinaprofessoranoletivo.to_param, :cursodisciplinaprofessoranoletivo => valid_attributes}, valid_session
        response.should redirect_to(cursodisciplinaprofessoranoletivo)
      end
    end

    describe "with invalid params" do
      it "assigns the cursodisciplinaprofessoranoletivo as @cursodisciplinaprofessoranoletivo" do
        cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessoranoletivo.any_instance.stub(:save).and_return(false)
        put :update, {:id => cursodisciplinaprofessoranoletivo.to_param, :cursodisciplinaprofessoranoletivo => {}}, valid_session
        assigns(:cursodisciplinaprofessoranoletivo).should eq(cursodisciplinaprofessoranoletivo)
      end

      it "re-renders the 'edit' template" do
        cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cursodisciplinaprofessoranoletivo.any_instance.stub(:save).and_return(false)
        put :update, {:id => cursodisciplinaprofessoranoletivo.to_param, :cursodisciplinaprofessoranoletivo => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cursodisciplinaprofessoranoletivo" do
      cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
      expect {
        delete :destroy, {:id => cursodisciplinaprofessoranoletivo.to_param}, valid_session
      }.to change(Cursodisciplinaprofessoranoletivo, :count).by(-1)
    end

    it "redirects to the cursodisciplinaprofessoranoletivos list" do
      cursodisciplinaprofessoranoletivo = Cursodisciplinaprofessoranoletivo.create! valid_attributes
      delete :destroy, {:id => cursodisciplinaprofessoranoletivo.to_param}, valid_session
      response.should redirect_to(cursodisciplinaprofessoranoletivos_url)
    end
  end

end
