require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CursosController do

  # This should return the minimal set of attributes required to create a valid
  # Curso. As you add validations to Curso, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CursosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cursos as @cursos" do
      curso = Curso.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cursos).should eq([curso])
    end
  end

  describe "GET show" do
    it "assigns the requested curso as @curso" do
      curso = Curso.create! valid_attributes
      get :show, {:id => curso.to_param}, valid_session
      assigns(:curso).should eq(curso)
    end
  end

  describe "GET new" do
    it "assigns a new curso as @curso" do
      get :new, {}, valid_session
      assigns(:curso).should be_a_new(Curso)
    end
  end

  describe "GET edit" do
    it "assigns the requested curso as @curso" do
      curso = Curso.create! valid_attributes
      get :edit, {:id => curso.to_param}, valid_session
      assigns(:curso).should eq(curso)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Curso" do
        expect {
          post :create, {:curso => valid_attributes}, valid_session
        }.to change(Curso, :count).by(1)
      end

      it "assigns a newly created curso as @curso" do
        post :create, {:curso => valid_attributes}, valid_session
        assigns(:curso).should be_a(Curso)
        assigns(:curso).should be_persisted
      end

      it "redirects to the created curso" do
        post :create, {:curso => valid_attributes}, valid_session
        response.should redirect_to(Curso.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved curso as @curso" do
        # Trigger the behavior that occurs when invalid params are submitted
        Curso.any_instance.stub(:save).and_return(false)
        post :create, {:curso => {}}, valid_session
        assigns(:curso).should be_a_new(Curso)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Curso.any_instance.stub(:save).and_return(false)
        post :create, {:curso => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested curso" do
        curso = Curso.create! valid_attributes
        # Assuming there are no other cursos in the database, this
        # specifies that the Curso created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Curso.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => curso.to_param, :curso => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested curso as @curso" do
        curso = Curso.create! valid_attributes
        put :update, {:id => curso.to_param, :curso => valid_attributes}, valid_session
        assigns(:curso).should eq(curso)
      end

      it "redirects to the curso" do
        curso = Curso.create! valid_attributes
        put :update, {:id => curso.to_param, :curso => valid_attributes}, valid_session
        response.should redirect_to(curso)
      end
    end

    describe "with invalid params" do
      it "assigns the curso as @curso" do
        curso = Curso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Curso.any_instance.stub(:save).and_return(false)
        put :update, {:id => curso.to_param, :curso => {}}, valid_session
        assigns(:curso).should eq(curso)
      end

      it "re-renders the 'edit' template" do
        curso = Curso.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Curso.any_instance.stub(:save).and_return(false)
        put :update, {:id => curso.to_param, :curso => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested curso" do
      curso = Curso.create! valid_attributes
      expect {
        delete :destroy, {:id => curso.to_param}, valid_session
      }.to change(Curso, :count).by(-1)
    end

    it "redirects to the cursos list" do
      curso = Curso.create! valid_attributes
      delete :destroy, {:id => curso.to_param}, valid_session
      response.should redirect_to(cursos_url)
    end
  end

end
